---
- name: Install Bitwarden CLI
  become: true
  block:
    - name: Ensure dependencies are installed
      ansible.builtin.package:
        name:
          - curl
          - jq
          - libsecret-1-0
          - unzip
        state: present
        update_cache: true

    - name: Download Bitwarden CLI.zip
      ansible.builtin.get_url:
        url: "https://github.com/bitwarden/clients/releases/download/cli-v2025.1.3/bw-linux-2025.1.3.zip"
        dest: "/tmp/bw-linux-2025.1.3.zip"
        owner: bwdc
        group: bwdc
        mode: '0644'
        timeout: 60
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 10
      ignore_errors: true

    - name: Extract binary from zip
      ansible.builtin.unarchive:
        src: "/tmp/bw-linux-2025.1.3.zip"
        dest: /tmp/
        owner: bwdc
        group: bwdc
        mode: '0755'
        remote_src: true

    - name: Move binary to /usr/local/bin
      ansible.builtin.command:
        cmd: mv /tmp/bw /usr/local/bin/bw
        creates: /usr/local/bin/bw
      become_user: root

    - name: Set permissions on bw binary
      ansible.builtin.file:
        path: /usr/local/bin/bw
        owner: bwdc
        group: bwdc
        mode: '0755'

    - name: Verify installation
      ansible.builtin.command: bw --version
      register: bw_version_output

    - name: Display version
      ansible.builtin.debug:
        msg: "Bitwarden CLI version is {{ bw_version_output.stdout }}"

    - name: Clean up temporary files
      ansible.builtin.file:
        path: /tmp/bw-linux-2025.1.3.zip
        state: absent

...

